In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/adult .csv",names=['Age','Workclass','Fnlwgt','Education','education_num','marital_status','occupation','relationship','race',
                                              'sex','capital_gain','capital_loss','hours_per_week','native_country','income'])
data

Age          Workclass  Fnlwgt    Education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [ ]:
data.isnull().any().sum()


0

In [ ]:
data = pd.DataFrame(data)
data.head()

data_dummies = pd.get_dummies(data)
data_dummies.head()


Age  Fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Workclass_ ?  Workclass_ Federal-gov  Workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   

   Workclass_ Never-worked  ...  native_country_ Scotland  \
0                        0  ...                         0   
1                        0  ...                         0   
2                        0  ...                         0   
3                        0  ...                         0   
4                        0  ...                         0   

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                        0                           0              1   
1                        0                           0              1   
2                        0                           0              1   
3                        0                           0              1   
4                        0                           0              1   

   income_ >50K  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 110 columns]

In [ ]:
x = data_dummies.iloc[:,:-2].values
y = data_dummies.iloc[:,-1].values



In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2,random_state=1)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)
y_pred


array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,hamming_loss
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix \n",cm)
a = accuracy_score(y_test,y_pred)
print("\nAccuracy_score :",a)
print("Classification_report : \n",classification_report(y_test,y_pred)) 
hamming_loss = hamming_loss(y_test, y_pred)
print("Misclassification : ",hamming_loss)


Confusion Matrix 
 [[4382  644]
 [ 552  935]]

Accuracy_score : 0.8163672654690619
Classification_report : 
               precision    recall  f1-score   support

           0       0.89      0.87      0.88      5026
           1       0.59      0.63      0.61      1487

    accuracy                           0.82      6513
   macro avg       0.74      0.75      0.74      6513
weighted avg       0.82      0.82      0.82      6513

Misclassification :  0.18363273453093812


Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier1 = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier1.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred1 = classifier1.predict(x_test)

In [ ]:
#Reshaping the y_pred
print(np.concatenate((y_pred1.reshape(len(y_pred1),1),y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,hamming_loss
cm = confusion_matrix(y_test,y_pred1)
print("Confusion Matrix \n",cm)
a = accuracy_score(y_test,y_pred1)
print("\nAccuracy_score :",a)
print("Classification_report : \n",classification_report(y_test,y_pred1)) 
hamming_loss = hamming_loss(y_test, y_pred1)
print("Misclassification : ",hamming_loss)


Confusion Matrix 
 [[4653  373]
 [ 611  876]]

Accuracy_score : 0.8489175495163519
Classification_report : 
               precision    recall  f1-score   support

           0       0.88      0.93      0.90      5026
           1       0.70      0.59      0.64      1487

    accuracy                           0.85      6513
   macro avg       0.79      0.76      0.77      6513
weighted avg       0.84      0.85      0.84      6513

Misclassification :  0.1510824504836481


Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state=1)
classifier2.fit(x_train,y_train)

y_pred2 = classifier2.predict(x_test)


In [ ]:
#Reshaping the y_pred
print(np.concatenate((y_pred2.reshape(len(y_pred2),1),y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,hamming_loss
cm = confusion_matrix(y_test,y_pred2)
print("Confusion Matrix \n",cm)
a = accuracy_score(y_test,y_pred2)
print("\nAccuracy_score :",a)
print("Classification_report : \n",classification_report(y_test,y_pred2)) 
hamming_loss = hamming_loss(y_test, y_pred2)
print("Misclassification : ",hamming_loss)


Confusion Matrix 
 [[4624  402]
 [ 571  916]]

Accuracy_score : 0.8506064793489944
Classification_report : 
               precision    recall  f1-score   support

           0       0.89      0.92      0.90      5026
           1       0.69      0.62      0.65      1487

    accuracy                           0.85      6513
   macro avg       0.79      0.77      0.78      6513
weighted avg       0.85      0.85      0.85      6513

Misclassification :  0.14939352065100567


KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier3 = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier3.fit(x_train,y_train)

y_pred3 = classifier3.predict(x_test)


In [ ]:
#Reshaping the y_pred
print(np.concatenate((y_pred3.reshape(len(y_pred3),1),y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,hamming_loss
cm = confusion_matrix(y_test,y_pred3)
print("Confusion Matrix \n",cm)
a = accuracy_score(y_test,y_pred3)
print("\nAccuracy_score :",a)
print("Classification_report : \n",classification_report(y_test,y_pred3)) 
hamming_loss = hamming_loss(y_test, y_pred3)
print("Misclassification : ",hamming_loss)


Confusion Matrix 
 [[4480  546]
 [ 605  882]]

Accuracy_score : 0.8232765238753262
Classification_report : 
               precision    recall  f1-score   support

           0       0.88      0.89      0.89      5026
           1       0.62      0.59      0.61      1487

    accuracy                           0.82      6513
   macro avg       0.75      0.74      0.75      6513
weighted avg       0.82      0.82      0.82      6513

Misclassification :  0.17672347612467373


Support Vector Machine (With Linear Kernel)

In [ ]:
from sklearn.svm import SVC
classifier4 = SVC()
classifier4.fit(x_train,y_train)

y_pred4 = classifier4.predict(x_test)


In [ ]:
print(np.concatenate((y_pred4.reshape(len(y_pred4),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,hamming_loss
cm = confusion_matrix(y_test,y_pred4)
print("Confusion Matrix \n",cm)
a = accuracy_score(y_test,y_pred4)
print("\nAccuracy_score :",a)
print("Classification_report : \n",classification_report(y_test,y_pred4)) 
hamming_loss = hamming_loss(y_test, y_pred4)
print("Misclassification : ",hamming_loss) 



Confusion Matrix 
 [[4671  355]
 [ 614  873]]

Accuracy_score : 0.8512206356517734
Classification_report : 
               precision    recall  f1-score   support

           0       0.88      0.93      0.91      5026
           1       0.71      0.59      0.64      1487

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.77      6513
weighted avg       0.84      0.85      0.85      6513

Misclassification :  0.1487793643482266
